# Copyright (C) 2019 SCARV project <info@scarv.org>
#
# Use of this source code is restricted per the MIT license, a copy of which 
# can be found at https://opensource.org/licenses/MIT (or should be included 
# as LICENSE.txt within the associated archive or repository).

# =============================================================================

ENV RISCV "${DEPS}/riscv"

RUN apt-get --assume-yes --quiet install make autoconf automake autotools-dev bc bison build-essential curl device-tree-compiler flex gawk gcc git gperf libexpat-dev libgmp-dev libmpc-dev libmpfr-dev libtool libusb-1.0-0-dev patchutils pkg-config texinfo zlib1g-dev \
 && git clone https://github.com/riscv/riscv-gnu-toolchain \
 && cd ./riscv-gnu-toolchain \
 && git submodule update --init --recursive \
 && ./configure --prefix="${RISCV}" --with-arch="rv32imac" --with-abi="ilp32" \
 && make \
 && cd .. \
 && rm --force --recursive ./riscv-gnu-toolchain \
 && git clone https://github.com/riscv/riscv-tools.git \
 && cd ./riscv-tools \
 && git submodule update --init --recursive \
 && ./build-rv32ima.sh \
 && cd .. \
 && rm --force --recursive ./riscv-tools

ENV PATH "${RISCV}/bin:${PATH}"

# =============================================================================
