# Copyright (C) 2019 SCARV project <info@scarv.org>
#
# Use of this source code is restricted per the MIT license, a copy of which 
# can be found at https://opensource.org/licenses/MIT (or should be included 
# as LICENSE.txt within the associated archive or repository).

# The build seems to trigger an existing bug, see, e.g., [1], related to the 
# maximum path length supported by the underlying file system: we'll create 
# a path that cannot then be removed.  The fix is simple: we just relocate a 
# sub-directory, shortening the path so it *can* then be removed.
# 
# [1] https://github.com/moby/moby/issues/13451

ENV RISCV "/opt/riscv"

RUN apt-get --assume-yes --quiet install make autoconf automake autotools-dev bc bison build-essential curl device-tree-compiler flex gawk gcc git gperf libexpat-dev libgmp-dev libmpc-dev libmpfr-dev libtool libusb-1.0-0-dev patchutils pkg-config texinfo zlib1g-dev \
 && git clone https://github.com/riscv/riscv-gnu-toolchain \
 && cd ./riscv-gnu-toolchain \
 && git submodule update --init --recursive \
 && ./configure --prefix=${RISCV} --with-arch=rv32imac --with-abi=ilp32 \
 && make \
 && mv ./build/build-gdb-newlib/gnulib/confdir3/confdir3 ./bugfix && rm --force --recursive ./bugfix \
 && cd .. \
 && rm --force --recursive ./riscv-gnu-toolchain \
 && git clone https://github.com/riscv/riscv-tools.git \
 && cd ./riscv-tools \
 && git submodule update --init --recursive \
 && ./build-rv32ima.sh \
 && cd .. \
 && rm --force --recursive ./riscv-tools
