#ifndef __CONF_H
#define __CONF_H

#define CONF_AES_ENABLE_ENC   ${CONF_AES_ENABLE_ENC}
#define CONF_AES_ENABLE_DEC   ${CONF_AES_ENABLE_DEC}

#define CONF_AES_PRECOMP_SBOX ${CONF_AES_PRECOMP_SBOX}
#define CONF_AES_PRECOMP_TBOX ${CONF_AES_PRECOMP_TBOX}
#define CONF_AES_PRECOMP_MULX ${CONF_AES_PRECOMP_MULX}
#define CONF_AES_PRECOMP_DIVX ${CONF_AES_PRECOMP_DIVX}
#define CONF_AES_PRECOMP_RC   ${CONF_AES_PRECOMP_RC}
#define CONF_AES_PRECOMP_RK   ${CONF_AES_PRECOMP_RK}

#define CONF_AES_KEY_FWD      ${CONF_AES_KEY_FWD}
#define CONF_AES_KEY_REV      ${CONF_AES_KEY_REV}

#define CONF_AES_ROUND_SPLIT  ${CONF_AES_ROUND_SPLIT}
#define CONF_AES_ROUND_PACK   ${CONF_AES_ROUND_PACK}
#define CONF_AES_ROUND_UNROLL ${CONF_AES_ROUND_UNROLL}

#endif
